### ISSUE TITLE
forge access?

### ISSUE THREAD

**Issue by logicminds** [nanliu/puppet-git#8]
Did you remove this from the forge or migrate to some other namespace?

**Comment by logicminds** [comment]
Ok, now I remember it was never in the forge on purpose I assume.

**Comment by nanliu** [comment]
Correct, it's not on forge. @nibalizer should I move this module to puppet-community? Especially since it seems like you are including this into openstack modules.

**Comment by nibalizer** [comment]
Ya moving it to the puppet community seems like a good call. We can wire up autodeploys once it is there.
